dist: xenial

sudo: false

language: python

python:
  - '3.5'

matrix:
  include:
    - os: linux
      env: PLATFORM=amd64
    - os: linux
      env: PLATFORM=armv7l

services:
  - docker

script:
  # Docker is used for cross compiling the binaries for 32-bit Linux and armv7l.
  # Build the image, create a container from the image and get the container ID.
  # Finally copy over the wheel to the host.
  - if [[ "$PLATFORM" == "armv7l" ]]; then
      docker build -f Dockerfile.$PLATFORM -t lauszus/socketsocketcan .;
      CONTAINER_ID=$(docker create lauszus/socketsocketcan);
      docker cp $CONTAINER_ID:/wheels wheels;
    else
      python3 -m pip install -U pip setuptools wheel pybind11;
      python3 -m pip -v wheel --build=build --wheel-dir=wheels .;
      python3 -m pip install --find-links=wheels socketsocketcan;
      python3 -c "import socketsocketcan; print(dir(socketsocketcan))";
    fi

deploy:
  provider: releases
  api_key:
    secure: SU6ycTt3Hnf+2fgY329AL93xs9UW1RZK+wcF3FBGyKnUEE43XcRq56UIu+2L0Vdte8YWYBIywCpozG5boBzXFf4v7ybsLKBB9EW7rY5LCGJVvgKYSLv/q/V/50K6tIGhtMzjuig/k0Z8Bw+z+0U4/17hOWWpwuZxH+d5K0feW+EzgZ/rSWTtxRlMhSOM30SDvPq7VaY6HqF09xFRtL5PIdA8iy39+pQo7wPOXnVZ7TOJl90qYm4ICOi7Ipg41+C/34nhIF4+Eo9nqWVF+egnoiXJIJY6uScYsrIwYt0q0edx16uxmdAfM6rmYPaaeg3ovLL+YVp7GhFEz8bqPdB58lvhVD+VdR2hfCrUpS9lJm1v/ShCGMJNiVRV22ZzBoaPfY0gVDrDMShRtyfIb5Z/TZDxfr9DL9eB9ZGn2SaaGaB3P0uFSBTZhchiX0AUWEJ+rIKbi4f6YlHc722JjpkPX+MZNecTLGlWB4LWfbE4yihcHFthg8qYVKky5ptDKVDvFad2jrrl6/TpUBUhvyF142lO3YQeRKLSFwHWmWInKwcyyR/kUGsBL9816YAoq9uJDb4Ah6YEaOwAi1HagyrkbyrVePgHZTJE50HDMyqX/JcbjFB3a10rT/Sr5vQg919ajdFasV4zACQxP8qAwS/0eF5kErZZw6CY0kk8ajX+XOA=
  file_glob: true
  file: "wheels/socketsocketcan*.whl"
  skip_cleanup: true
  on:
    tags: true
